### ISSUE TITLE
关于win签名的问题

### ISSUE THREAD

**Issue by Paimon-Kawaii** [Miuwiki/L4D2plguin.Map-vpk-chooser.#1]
貌似这个评论已经给出了正确的签名和地址了（没有仔细验证过，只是在ida里看了一下）
https://forums.alliedmods.net/showpost.php?p=2816204&postcount=4

**Comment by Miuwiki** [comment]
> 貌似这个评论已经给出了正确的签名和地址了（没有仔细验证过，只是在ida里看了一下） https://forums.alliedmods.net/showpost.php?p=2816204&postcount=4

该帖子的windows提供的是show_addon_metadata的签名, 不是vecAddonMetadata.
我在windows上测试没有通过.
![图片](https://github.com/Miuwiki/L4D2plguin.Map-vpk-chooser/assets/87111612/99e91ae1-32d4-42d0-a614-9f72e57f27d4)

**Comment by Paimon-Kawaii** [comment]
![image](https://github.com/Miuwiki/L4D2plguin.Map-vpk-chooser/assets/77665174/4ead5463-f1e4-4402-86d7-53b9e416aa47)
![image](https://github.com/Miuwiki/L4D2plguin.Map-vpk-chooser/assets/77665174/0b06869d-69c5-490b-9aba-7e27299689f7)
![image](https://github.com/Miuwiki/L4D2plguin.Map-vpk-chooser/assets/77665174/e7265884-3c9d-42b3-ad13-c41361637c58)
根据对比图可以看出应该是这个没错，签名我验证了一下没有问题，应该是字节读错了，~~read应该是50，在我的电脑上测试通过了。~~
~~50也不对，我再看看。~~
是49，已经成功了
![image](https://github.com/Miuwiki/L4D2plguin.Map-vpk-chooser/assets/77665174/92623239-65ed-45f0-9c34-facf4b5aa82b)

**Comment by Paimon-Kawaii** [comment]
内存签名不是很好弄，你还是用读地址的方式更好一些
![image](https://github.com/Miuwiki/L4D2plguin.Map-vpk-chooser/assets/77665174/80fad00f-c633-4a4d-ac5c-aa366eaeacb9)
![image](https://github.com/Miuwiki/L4D2plguin.Map-vpk-chooser/assets/77665174/33c81eda-2cb5-41e7-b821-4bd252be3b5d)

**Comment by Miuwiki** [comment]
> 内存签名不是很好弄，你还是用读地址的方式更好一些 ![image](https://private-user-images.githubusercontent.com/77665174/299882845-80fad00f-c633-4a4d-ac5c-aa366eaeacb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTk2NTEsIm5iZiI6MTcwNjI1OTM1MSwicGF0aCI6Ii83NzY2NTE3NC8yOTk4ODI4NDUtODBmYWQwMGYtYzYzMy00YTRkLWFjNWMtYWEzNjZlYWVhY2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA4NTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMjUzZWU1NmIyZDdlNzk2NTZjMDI3NGUyNDM0MzVkM2U4ZTY1YTgyZWRiZTYxMTIwZjkyNWIwNGM3ZGFkYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cuw7lh_tRT-AkWvWRSwRaUTQ9xvTfzd2rShcgaY69V0) ![image](https://private-user-images.githubusercontent.com/77665174/299883897-33c81eda-2cb5-41e7-b821-4bd252be3b5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTk2NTEsIm5iZiI6MTcwNjI1OTM1MSwicGF0aCI6Ii83NzY2NTE3NC8yOTk4ODM4OTctMzNjODFlZGEtMmNiNS00MWU3LWI4MjEtNGJkMjUyYmUzYjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA4NTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZTU4ODg2Y2FhNjQ4NjlkMjYwYmRlNTI2MzY5YjVjZmFhMDBiNDM0YWI0ZmRjNmIzZDBjODFjMmU2ZWQ3ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UFuuh7DYtC9RHjjkmyKwJ3kn_Ofjz88EWCYdPX9x3LQ)

制作完成了, 另外也修复了内存读取超出的问题, 不再使用addonlist.txt内的文件总数作为循环次数, 直接获取show_addon_metadata命令使用的循环变量.

那个评论给的插件读取过于复杂了, 整个struct就是128 + 128 + 8的大小, 读两个字符串加一个unsigned int. 然后整体偏移264读取下一个struct就行了. 他的插件还有那个unknown也不清楚为什么.
